# Generated by Django 6.0.7 on 2026-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='request_example',
            field=models.JSONField(blank=True, default=dict, help_text='Documents expected query params / request body'),
        ),
    ]
