# Generated by Django 6.0.7 on 2026-07-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_endpoint_description_endpoint_request_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='mode',
            field=models.CharField(choices=[('static', 'Static response'), ('stateful', 'Stateful CRUD on a resource')], default='static', max_length=8),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('initial_items', models.JSONField(blank=True, default=list)),
                ('items', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='mocks.project')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_resource_per_project')],
            },
        ),
    ]
