# Generated by Django 6.0.7 on 2026-07-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_endpoint_mode_endpoint_resource_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
